### ISSUE TITLE
USER STORY: Single listing View

### ISSUE THREAD

**Issue by naisepaul** [naisepaul/petlover-project#17]
As a **user** I want to be able to **view detailed information about a single puppies** so that I can **make an informed decision before going to the next steps**

**Acceptance Criteria:**

- Given I am on the homepage or "All listings" page, When I click on a listing's title or image, Then I should be redirected to a "Single listings View" page.

- Given I am on the "Single listings Views" page, When I view the page, Then I should see detailed information about the selected listings, including:

1.   The dog's breed
2.   Photo
3.  Temperament
4.  DOB
5.  Seller details

-  Given I am on the "Single listings View" page, When I click on the "Go Back" button, Then I should be directed back to the previous page (e.g., the "All listings" page or the homepage).
-   Given I am on the "Single listings View" page, When I click on the "profile picture" for the seller, Then I should be directed back to seller profile details.

**Tasks:**

- [x]  Create a Django view for displaying single listings display.
- [x]  Create a template for the "single listings" page to render the selected listings information.
- [x]  Implement URL routing for the "Single listings View" page.
- [x]  Ensure that clicking on a listing's title or image from the homepage or "All listings" page redirects to the "Single listing View."
- [x]  Implement a "Go Back" button to allow users to navigate back to the previous page.
- [x] Implement a clickable link for seller profile picture to go back to the seller profile details
